import { DEFAULT_MATCHER_PROFILE, compositionId, sizeRatioRulesFromSlots, type EncodedBinaryMask, type ModularSpriteSchema, type SchemaSlot } from '@kukla2d/modular-sprite-schema';

const exampleAssetUrls = import.meta.glob<string>(
  '../../../modular-sprite/assets/examples/*.png',
  { eager: true, query: '?url', import: 'default' },
);

interface ComponentFixture {
  bounds: { x: number; y: number; width: number; height: number };
  centroid: { x: number; y: number };
  foregroundAreaRatio: number;
  boundingBoxAreaRatio: number;
  aspectRatio: number;
  mask: string;
}

function decodeMask(hex: string): EncodedBinaryMask {
  const data = new Uint8Array(1024);
  for (let nibble = 0; nibble < hex.length; nibble += 1) {
    const value = Number.parseInt(hex[nibble]!, 16);
    for (let bit = 0; bit < 4; bit += 1) data[nibble * 4 + bit] = (value >> (3 - bit)) & 1;
  }
  return { width: 32, height: 32, data };
}

function slot(slotKey: string, role: string, drawOrder: number, fixture: ComponentFixture, qualifiers: Record<string, string> = {}): SchemaSlot {
  return {
    slotKey,
    label: slotKey.split('-').map(value => value[0]!.toUpperCase() + value.slice(1)).join(' '),
    semanticRoleId: `builtin.part-role.${role}`,
    qualifiers,
    required: true,
    drawOrder,
    components: [{ componentKey: `${slotKey}-1`, bounds: fixture.bounds, centroid: fixture.centroid, foregroundAreaRatio: fixture.foregroundAreaRatio, boundingBoxAreaRatio: fixture.boundingBoxAreaRatio, aspectRatio: fixture.aspectRatio, shapeMask: decodeMask(fixture.mask) }],
  };
}

function make(input: { schemaId: string; name: string; slots: SchemaSlot[]; aspectRatio: number; foregroundBounds: { x: number; y: number; width: number; height: number }; width: number; height: number; classes: string[] }): ModularSpriteSchema {
  const profile = structuredClone(DEFAULT_MATCHER_PROFILE);
  profile.sizeRatioRules = sizeRatioRulesFromSlots(input.slots);
  const updatedAt = '2026-09-04T18:10:00.000Z';
  return { formatVersion: 1, schemaId: input.schemaId, revision: 1, compositionId: compositionId(input.slots), name: input.name, description: 'Fingerprint generated by the production processor from the matching built-in example.', characterTypeIds: ['builtin.character-type.humanoid'], characterClassIds: input.classes, tags: ['built-in', 'example', 'humanoid'], slots: input.slots, fingerprint: { canvasAspectRatio: input.aspectRatio, foregroundBounds: input.foregroundBounds, slots: input.slots, expectedIslandCount: input.slots.length }, matcherProfile: profile, referenceAsset: { assetId: `builtin.asset.${input.schemaId}`, mimeType: 'image/png', width: input.width, height: input.height }, origin: { kind: 'builtin', sourceId: 'kukla2d' }, createdAt: updatedAt, updatedAt };
}

const panda: ComponentFixture[] = [
  { bounds: { x: .20334928229665072, y: .025518341307814992, width: .36044657097288674, height: .3149920255183413 }, centroid: { x: .39649010419175845, y: .18906607490470959 }, foregroundAreaRatio: .08627320803095168, boundingBoxAreaRatio: .11353779548189016, aspectRatio: 1.1443037974683545, mask: '0078000000fc000001fefcf803fffff803fffffc07fffffc07fffffc07fffffc07fffffc07fffffc07fffff807fffff80ffffffc0ffffffe0ffffffe0ffffffe1ffffffe3ffffffe7ffffffe7ffffffe7ffffffe7ffffffeffffffffffffffff7fffffff3fffffff1fffffff0fffffff06ffffff0279ffcf001c3f8700040003' },
  { bounds: { x: .03827751196172249, y: .32137161084529503, width: .19537480063795853, height: .310207336523126 }, centroid: { x: .14337306744393058, y: .47698973111329024 }, foregroundAreaRatio: .03945524242678612, boundingBoxAreaRatio: .060606696529637856, aspectRatio: .6298200514138818, mask: '00003f800001fff00003fff80007fffc001ffffe003fffff00ffffff00ffffff00ffffff07ffffff1ffffffe3ffffffc3ffffff01fffffc01fffffc007ffff000ffffe001fffff001fffff00ffffff003fffff800fffffe007fffff807fffff807fffffc1ffffff800fffff8007ffff8003ffff8000ffff00007ff800003ff00' },
  { bounds: { x: .5629984051036683, y: .34290271132376393, width: .22807017543859648, height: .21770334928229665 }, centroid: { x: .670751988608767, y: .4602711130005085 }, foregroundAreaRatio: .027219436876953874, boundingBoxAreaRatio: .049651641064383446, aspectRatio: 1.0476190476190477, mask: '00c0000003e000000ff000001ff800003ffc00007ffe00007fff0000ffff0000ffff0000ffff0000ffff8000ffff8000ffffe0007ffff3007fffff803fffffc03fffffe01ffffffc0ffffffe0ffffffe07ffffff03ffffff03ffffff01ffffff00fffffe000ffffc0003fffc0003fffc0003fff80001fff000007fe000001ec0' },
  { bounds: { x: .2631578947368421, y: .361244019138756, width: .2894736842105263, height: .3580542264752791 }, centroid: { x: .41177832326367414, y: .5270186456505886 }, foregroundAreaRatio: .079432578110493, boundingBoxAreaRatio: .10364727608494921, aspectRatio: .8084632516703786, mask: '0303a0000fffff800ffffff03ffffff87ffffff87ffffffe7ffffffefffffffefffffffefffffffffffffffeffffffff7ffffffe3ffffffe1ffffffe0ffffffc0ffffffc0ffffffc0ffffffc07fffffe0ffffffe0ffffffe1fffffff1fffffff3ffffffe1ffffffe3ffffffe07ffffb000ffff000001ff0000007c0000000800' },
  { bounds: { x: .6379585326953748, y: .5255183413078149, width: .3413078149920255, height: .40749601275917063 }, centroid: { x: .8328096857160705, y: .7128860335221991 }, foregroundAreaRatio: .06466643264679024, boundingBoxAreaRatio: .1390815737327951, aspectRatio: .837573385518591, mask: '000010040000700c0003f01e000ff07e001feefe001ffc7e003ffcff003fffff003fffff003fffff0033ffff0027ffff000fffff000ffffc001ffffe003ffffe007ffffc007ffff800fffff001f3ffc003e1ffc007c1ff800fc1fe001f83f8003f02f0003e00f0007f00f800fe00f800fc007000fc003000f000100040000000' },
  { bounds: { x: .19936204146730463, y: .7352472089314195, width: .1722488038277512, height: .21052631578947367 }, centroid: { x: .2794813080667231, y: .8550589532988134 }, foregroundAreaRatio: .024818825372841993, boundingBoxAreaRatio: .036262906069000254, aspectRatio: .8181818181818182, mask: '001f8000007fe00000fff00001fff80003fffc0007fffc0007fffe0007ffff000fffff800fffffc00fffff800fffff800fffff801fffff003fffff003fffff001ffffe001fffff001fffff001fffff803fffff803fffffe07ffffff87ffffffcfffffffefffffffeffffffffffffffffffffffff7fffffff07ffffff000ffff0' },
  { bounds: { x: .4130781499202552, y: .7360446570972887, width: .17783094098883573, height: .2113237639553429 }, centroid: { x: .49369591571937044, y: .8578784825540954 }, foregroundAreaRatio: .025046486013496842, boundingBoxAreaRatio: .03757990379748123, aspectRatio: .8415094339622642, mask: '001f8000007fe00000fff00001fff80003fff80007fffc0007fffc0007fffc000ffffe000ffffe000ffffe000ffffe000ffffe003ffffe003ffffc003ffffc003ffffc001ffffe001fffff003fffff803fffff803fffffe03ffffff87ffffffcfffffffefffffffeffffffffffffffffffffffffffffffff07fffffe001ffff0' },
];

const wizard: ComponentFixture[] = [
  { bounds: { x: .19298245614035087, y: .037480063795853266, width: .32456140350877194, height: .3508771929824561 }, centroid: { x: .34434830385122783, y: .20669430850717402 }, foregroundAreaRatio: .06696275268423342, boundingBoxAreaRatio: .11388119421360418, aspectRatio: .925, mask: '0078000003ff00003fff80007fffe0007ffff800fffffc00e7fffe00c3ffff0003ffff8003ffff8007ffffc007ffffc007ffffc00fffffe00fffffe01ffffff03ffffff83ffffffe3fffffff7ffffffc7fffffc0ffffffc007ffff8003ffffc000ffffe001ffffc0001fffc0000fff800003ff800001fe0000007c0000001800' },
  { bounds: { x: .7272727272727273, y: .09170653907496013, width: .12360446570972887, height: .3700159489633174 }, centroid: { x: .776041182411548, y: .2385371626744305 }, foregroundAreaRatio: .018882478779230227, boundingBoxAreaRatio: .045735623675689153, aspectRatio: .33405172413793105, mask: '000ffff0003fffff03fffffe03fffffe07fffffc07ffffe00fffffc01fffff000ffffe0007fffe0003ffe00003ff800003ff800003ff000003fe000007fc000007f8000007f8000003fc000007fc000007f800000ff000003fe000007fe000003fe000003ff000003ff000003ff000007fe00000ffe00000ffc000003f800000' },
  { bounds: { x: .266347687400319, y: .430622009569378, width: .2703349282296651, height: .2711323763955343 }, centroid: { x: .4012844080451843, y: .5731731902327157 }, foregroundAreaRatio: .05446240292626593, boundingBoxAreaRatio: .0732965515136253, aspectRatio: .9970588235294118, mask: '00fffe0001ffff0003ffff8003ffff8007ffff8007ffffc00fffffc00fffffe00fffffe00fffffe01ffffff01ffffff01ffffff83ffffff83ffffffc7ffffffe7ffffffc7ffffffc1ffffff801ffffe001fffff003fffff007fffff807fffff807fffff80ffffffc1ffffffe7ffffffeffffffffffffffff3ffffff8007fc000' },
  { bounds: { x: .5845295055821371, y: .4314194577352472, width: .11562998405103668, height: .18899521531100477 }, centroid: { x: .6377283122962127, y: .5300115677972269 }, foregroundAreaRatio: .014424654502720482, boundingBoxAreaRatio: .021853513732133727, aspectRatio: .6118143459915611, mask: '07f000001ffe00003fff00007fffc000ffffe000fffff000fffff800fffff800fffffc00fffffc007ffffe007ffffe003fffff003fffff003fffff803fffffc01fffffe01ffffff01ffffff80ffffffc0ffffffe0ffffffe0ffffffe07fffffc03fffffe01ffffff01ffffff00fffffe007ffff8007ffff0003fffc00007be00' },
  { bounds: { x: .06299840510366826, y: .43381180223285487, width: .11004784688995216, height: .25199362041467305 }, centroid: { x: .12175419510843137, y: .5636314470074534 }, foregroundAreaRatio: .019555921847536052, boundingBoxAreaRatio: .027731355356638662, aspectRatio: .43670886075949367, mask: '00007f800003ffe00007fff8001ffff8003ffffc007ffffc00fffff800fffff801fffff803fffff807fffff00ffffff00ffffff01ffffff03ffffff07ffffff0fffffff8fffffff8fffffffc7ffffffe7fffffff7fffffff7ffffffe7ffffffc7ffffffc0ffffffc01ffffff00ffffff00ffff38003fff800003ffc000001f80' },
  { bounds: { x: .7559808612440191, y: .5430622009569378, width: .06937799043062201, height: .10207336523125997 }, centroid: { x: .790124554864323, y: .5962357010727589 }, foregroundAreaRatio: .00457547013830066, boundingBoxAreaRatio: .00708164495623574, aspectRatio: .6796875, mask: '0007e000001ffc00003fff00007fff8000ffff8001ffffc003ffff8007ffff800fffff000fffffc003fffff001fffffc003ffffe003fffff007fffff01ffffff03ffffff07fffffe07fffffe1ffffffc3ffffff87ffffff0fffffff0ffffffc0ffffff80ffffff00fffffe007ffffc007ffff8001fffe00007ff8000007c0000' },
  { bounds: { x: .38915470494417864, y: .766347687400319, width: .14433811802232854, height: .14035087719298245 }, centroid: { x: .45434790129506114, y: .8521945750239135 }, foregroundAreaRatio: .012195742364465608, boundingBoxAreaRatio: .02025798147681804, aspectRatio: 1.0284090909090908, mask: '003e0000007f800000ffc00000ffc00001ffc00001ffe00001ffe00003ffe00003ffe00007ffe00007ffe00007ffe0000fffe0000fffe0000fffe0000fffe0001ffff0001ffff8301ffff8383ffff83c3ffffc3c3fffff3e7ffffffe7fffffff7ffffffffffffffffffffffffffffffffffffffefffffffe7ffffffc001fffc0' },
  { bounds: { x: .1722488038277512, y: .7671451355661882, width: .145933014354067, height: .13955342902711323 }, centroid: { x: .23865669902438622, y: .8526508651714868 }, foregroundAreaRatio: .01213215000674079, boundingBoxAreaRatio: .020365452561372985, aspectRatio: 1.0457142857142858, mask: '003e0000007f8000007fc00000ffc00000ffe00001ffe00001ffe00003ffe00003ffe00003ffe00007ffe00007ffe00007ffe0000fffe0000fffe0000fffe0000ffff0001ffff8201ffff8381ffff83c3ffffe3c3fffff3e7ffffffe7fffffff7ffffffffffffffffffffffffffffffffffffffefffffffe7ffffffc001fffc0' },
];

const pandaSlots = [slot('head', 'head', 7, panda[0]!), slot('left-arm', 'arm', 3, panda[1]!, { side: 'left' }), slot('right-arm', 'arm', 5, panda[2]!, { side: 'right' }), slot('torso', 'torso', 4, panda[3]!), slot('weapon', 'weapon', 6, panda[4]!, { side: 'right' }), slot('left-foot', 'foot', 1, panda[5]!, { side: 'left' }), slot('right-foot', 'foot', 2, panda[6]!, { side: 'right' })];
const wizardSlots = [slot('head', 'head', 8, wizard[0]!), slot('weapon', 'weapon', 7, wizard[1]!, { side: 'right' }), slot('torso', 'torso', 5, wizard[2]!), slot('right-arm', 'arm', 6, wizard[3]!, { side: 'right' }), slot('left-arm', 'arm', 4, wizard[4]!, { side: 'left' }), slot('hand', 'hand', 3, wizard[5]!, { side: 'right' }), slot('left-foot', 'foot', 1, wizard[6]!, { side: 'left' }), slot('right-foot', 'foot', 2, wizard[7]!, { side: 'right' })];

export const BUNDLED_SCHEMAS = [
  make({ schemaId: 'builtin.arcane-wizard', name: 'Arcane Wizard', slots: wizardSlots, aspectRatio: 1, foregroundBounds: { x: .06299840510366826, y: .037480063795853266, width: .7878787878787878, height: .8692185007974482 }, width: 1254, height: 1254, classes: ['builtin.character-class.wizard'] }),
  make({ schemaId: 'builtin.armored-panda', name: 'Armored Panda', slots: pandaSlots, aspectRatio: 1, foregroundBounds: { x: .03827751196172249, y: .025518341307814992, width: .9409888357256779, height: .9218500797448167 }, width: 1254, height: 1254, classes: ['builtin.character-class.knight'] }),
];

export const BUNDLED_SCHEMA_ASSET_URLS: Readonly<Record<string, string>> = {
  'builtin.asset.builtin.arcane-wizard': exampleAssetUrls['../../../modular-sprite/assets/examples/arcane-wizard.png']!,
  'builtin.asset.builtin.armored-panda': exampleAssetUrls['../../../modular-sprite/assets/examples/armored-panda.png']!,
};
