import { DEFAULT_MATCHER_PROFILE, compositionId, type EncodedBinaryMask, type ModularSpriteSchema, type SchemaSlot } from '@kukla2d/modular-sprite-schema';

interface ComponentFixture {
  bounds: { x: number; y: number; width: number; height: number };
  centroid: { x: number; y: number };
  foregroundAreaRatio: number;
  boundingBoxAreaRatio: number;
  aspectRatio: number;
  mask: string;
}

function decodeMask(hex: string): EncodedBinaryMask {
  const data = new Uint8Array(1024);
  for (let nibble = 0; nibble < hex.length; nibble += 1) {
    const value = Number.parseInt(hex[nibble]!, 16);
    for (let bit = 0; bit < 4; bit += 1) data[nibble * 4 + bit] = (value >> (3 - bit)) & 1;
  }
  return { width: 32, height: 32, data };
}

function slot(slotKey: string, role: string, drawOrder: number, fixture: ComponentFixture, qualifiers: Record<string, string> = {}): SchemaSlot {
  return {
    slotKey,
    label: slotKey.split('-').map(value => value[0]!.toUpperCase() + value.slice(1)).join(' '),
    semanticRoleId: `builtin.part-role.${role}`,
    qualifiers,
    required: true,
    drawOrder,
    components: [{ componentKey: `${slotKey}-1`, bounds: fixture.bounds, centroid: fixture.centroid, foregroundAreaRatio: fixture.foregroundAreaRatio, boundingBoxAreaRatio: fixture.boundingBoxAreaRatio, aspectRatio: fixture.aspectRatio, shapeMask: decodeMask(fixture.mask) }],
  };
}

function make(input: { schemaId: string; name: string; slots: SchemaSlot[]; aspectRatio: number; foregroundBounds: { x: number; y: number; width: number; height: number }; width: number; height: number; classes: string[] }): ModularSpriteSchema {
  const profile = structuredClone(DEFAULT_MATCHER_PROFILE);
  profile.sizeRatioRules = [{ ruleId: 'left-right-foot', leftSlotKey: 'left-foot', rightSlotKey: 'right-foot', metric: 'foreground-area', expectedRatio: input.slots.find(item => item.slotKey === 'left-foot')!.components[0]!.foregroundAreaRatio / input.slots.find(item => item.slotKey === 'right-foot')!.components[0]!.foregroundAreaRatio, tolerance: 0.15, weightBp: 10000 }, { ruleId: 'head-torso', leftSlotKey: 'head', rightSlotKey: 'torso', metric: 'bounds-area', expectedRatio: input.slots.find(item => item.slotKey === 'head')!.components[0]!.boundingBoxAreaRatio / input.slots.find(item => item.slotKey === 'torso')!.components[0]!.boundingBoxAreaRatio, tolerance: 0.2, weightBp: 10000 }];
  const updatedAt = '2026-09-04T18:10:00.000Z';
  return { formatVersion: 1, schemaId: input.schemaId, revision: 2, compositionId: compositionId(input.slots), name: input.name, description: 'Fingerprint generated by the production processor from the bundled reference image.', characterTypeIds: ['builtin.character-type.humanoid'], characterClassIds: input.classes, tags: ['bundled', 'humanoid'], slots: input.slots, fingerprint: { canvasAspectRatio: input.aspectRatio, foregroundBounds: input.foregroundBounds, slots: input.slots, expectedIslandCount: input.slots.length }, matcherProfile: profile, referenceAsset: { assetId: `builtin.asset.${input.schemaId}`, mimeType: 'image/png', width: input.width, height: input.height }, origin: { kind: 'builtin', sourceId: 'kukla2d' }, createdAt: updatedAt, updatedAt };
}

const v2: ComponentFixture[] = [
  { bounds: { x: .2183406113537118, y: .11717612809315867, width: .38165938864628823, height: .29621542940320233 }, centroid: { x: .4139674824042686, y: .2703457331495066 }, foregroundAreaRatio: .06978000673773066, boundingBoxAreaRatio: .11305339969362395, aspectRatio: 1.0737100737100738, mask: '0003c000000fc000001ff800007ffc0000ffff0001ffff8001ffff8003ffffc003ffffe007ffffe007ffffe007fffff007fffff007fffff007fffff03ffffffeffffffffffffffff3ffffffc1ffffff80ffffff80ffffff007fffff007fffff007fffff803fffff801fffff000ffffd000ffffc0000fff800003fe0000007c00' },
  { bounds: { x: .7537117903930131, y: .4519650655021834, width: .21921397379912663, height: .2197962154294032 }, centroid: { x: .8712687164197078, y: .553595947582016 }, foregroundAreaRatio: .016410823592227456, boundingBoxAreaRatio: .048182401810288385, aspectRatio: .8311258278145696, mask: '0000003f000003ff000003ff000007ff00000fff00001fff00003fff00007fff00007ffe0000fffc0001fff80003ffe00007ffc0000fff80000fff00001ffe00003ffc00007ff80000fff0000effc0001fff80001fff00001ffe00000ffc000007fc00000ffe00001ffc00003f3800007e000000fc0000007800000030000000' },
  { bounds: { x: .30305676855895197, y: .4556040756914119, width: .21048034934497817, height: .21542940320232898 }, centroid: { x: .41370255370148995, y: .5694917847451323 }, foregroundAreaRatio: .03621720918111147, boundingBoxAreaRatio: .045343656045206356, aspectRatio: .8141891891891891, mask: '0000f0000001f8000013fc0001fffff001fffff807fffff80ffffffc0ffffffe1ffffffe1ffffffe3fffffff3fffffff3fffffffffffffffffffffffffffffffffffffff7fffffff3ffffffe7ffffffe7ffffffe7fffffff7fffffff3fffffff3ffffffe3ffffffe3fffffff1ffffffe0ffffffe03fffff8003fffe0001ffc00' },
  { bounds: { x: .08122270742358079, y: .49053857350800584, width: .14148471615720523, height: .17394468704512372 }, centroid: { x: .15616395594205928, y: .5795384021775498 }, foregroundAreaRatio: .014440355192819868, boundingBoxAreaRatio: .024610514673633226, aspectRatio: .6778242677824268, mask: '000007f000003ffc0000fffe0003ffff0007ffff001fffff001fffff0007ffff0007fffe000ffffe001ffffc001ffffc001ffff8003ffff8007ffff000fffff001ffffe001ffffe007ffffc01fffffc03fffffc03fffff807fffff007fffff00fffffe00fffffe00fffffe00fffffc007ffffc000ffff00003ff0000003e0000' },
  { bounds: { x: .5772925764192139, y: .49344978165938863, width: .1589519650655022, height: .13682678311499272 }, centroid: { x: .6566033120631664, y: .5601932694391449 }, foregroundAreaRatio: .011608601412380898, boundingBoxAreaRatio: .021748886049719366, aspectRatio: .9680851063829787, mask: '0fc000003ff800007ffe00007fff0000ffff8000ffffc000ffffc000ffff80007fff80007fffe0003ffff0003ffffc001ffffe000fffff0007fffff003fffff803fffffc03fffffc03fffffe007ffffc003ffffe001ffffe001fffff000fffff0007ffff0003fffe0000fffc0000fffc00007ff000003fe000001fc000000780' },
  { bounds: { x: .25327510917030566, y: .7328966521106259, width: .1222707423580786, height: .15283842794759825 }, centroid: { x: .3174888180848085, y: .8153015578299195 }, foregroundAreaRatio: .013203409545965942, boundingBoxAreaRatio: .018687668045994546, aspectRatio: .6666666666666666, mask: '0007fc00001fff00007fffc000ffffe003fffff003fffff007fffff007fffff807fffff80ffffff807fffff007fffff007fffff007ffffe003ffffe003ffffe003ffffe003ffffe001ffffe001ffffc001ffffc001ffffc03dfffff0fffffffcfffffffefffffffe7fffffff0fffffff03ffffff03ffffff03ffffff03ffffff' },
  { bounds: { x: .434061135371179, y: .7336244541484717, width: .1205240174672489, height: .15138282387190685 }, centroid: { x: .4980568243566313, y: .8155871317961215 }, foregroundAreaRatio: .01293390031972439, boundingBoxAreaRatio: .018245266108579166, aspectRatio: .6634615384615384, mask: '0003fc00001fff80007fffc000ffffe001fffff003fffff803fffff807fffff807fffff807fffff807fffff807fffff807fffff003fffff003ffffe003ffffe003ffffe003ffffe001ffffe001ffffc001ffffc001ffffc03dfffff0fffffff8fffffffefffffffe7fffffff1fffffff07ffffff03ffffff03ffffff03ffffff' },
];

const wizard: ComponentFixture[] = [
  { bounds: { x: .1850079744816587, y: .024720893141945772, width: .3524720893141946, height: .3843700159489633 }, centroid: { x: .3482933730443643, y: .2089447493404713 }, foregroundAreaRatio: .07720938928443336, boundingBoxAreaRatio: .13547970259126138, aspectRatio: .91701244813278, mask: '0078000003fe00001fff80003fffc0007ffff0007ffff8007ffffc0073fffe0061ffff0003ffff0003ffff8007ffffc007ffffc00fffffc00fffffe01ffffff81ffffffe3fffffff3fffffff7ffffff8ffffff80ffffff8047ffffc001ffffc001ffffc0003fff80001fff800007ff800003fe000000fe0000003c0000001800' },
  { bounds: { x: .7121212121212122, y: .07177033492822966, width: .16188197767145135, height: .4226475279106858 }, centroid: { x: .7798520557974109, y: .23499370880748832 }, foregroundAreaRatio: .030222903932297034, boundingBoxAreaRatio: .06841901767613175, aspectRatio: .38301886792452833, mask: '0007fff0000fffff00ffffff03fffffe07fffffe07fffff80ffffff81fffffe01fffffc00fffff8007ffff8007ffff0007ff860003ff860007ff000007fc000007fc000003fc000007fc000007f800000ff000001ff000003fe000001ff000001ff000003fe000007ff000007fe00000ffe00000ffe000003f8000001c000000' },
  { bounds: { x: .2535885167464115, y: .42503987240829344, width: .291866028708134, height: .3014354066985646 }, centroid: { x: .3986308125504193, y: .5830258873760694 }, foregroundAreaRatio: .06516308896062106, boundingBoxAreaRatio: .0879787550651313, aspectRatio: .9682539682539683, mask: '007ffc0000ffff0001ffff8003ffff8003ffffc007ffffc007ffffc00fffffe00fffffe00ffffff01ffffff01ffffff01ffffff83ffffffc7ffffffc7ffffffe7ffffffc3ffffff007fffff007fffff007fffff00ffffff80ffffff81ffffff81ffffffc3ffffffeffffffffffffffffffffffff7ffffffc07ffe3f000030000' },
  { bounds: { x: .5725677830940988, y: .42503987240829344, width: .13875598086124402, height: .21610845295055822 }, centroid: { x: .6376782800559361, y: .5380134073928794 }, foregroundAreaRatio: .019407751654037225, boundingBoxAreaRatio: .02998634036156071, aspectRatio: .6420664206642066, mask: '03f800000ffe00001fff80003fffc0007fffe0007fffe000fffff000fffff000fffff8007ffff8007ffffc007ffffe007fffff003fffff001fffffc01fffffe01ffffff80ffffffc0ffffffc0ffffffe0ffffffc0ffffffc07fffffc07fffffe07ffffff03ffffff01fffffe00fffffc00fffff8003ffff0000fffc000003e00' },
  { bounds: { x: .05661881977671451, y: .4266347687400319, width: .1251993620414673, height: .2822966507177033 }, centroid: { x: .12358900376236, y: .5679143234585996 }, foregroundAreaRatio: .025073830727318513, boundingBoxAreaRatio: .03534336057629938, aspectRatio: .4435028248587571, mask: '00007f000003ffe0001ffff8007ffffc007ffffc00fffffe00fffffc01fffffc01fffffc03fffff807fffff80ffffff01ffffff03ffffff83ffffff07ffffff8fffffffc7ffffffcfffffffe7ffffffeffffffff7ffffffe7ffffff83ffffff807fffffc01fffffe01fffe7f00ffff3e007fff80000fffc000007fc000000f80' },
  { bounds: { x: .7472089314194578, y: .539872408293461, width: .0861244019138756, height: .12041467304625199 }, centroid: { x: .7894091246786922, y: .6027626256004772 }, foregroundAreaRatio: .0068927756537930296, boundingBoxAreaRatio: .01037064169776333, aspectRatio: .7152317880794702, mask: '000fc000001ff800003ffe00007fff8000ffff8001ffffc003ffffc007ffff800fffff800fffffe00ffffff807fffffc01fffffe007fffff00ffffff03ffffff07ffffff07fffffe1ffffffe3ffffffc7ffffff87ffffff0fffffff0ffffffe0ffffffc0ffffff807ffffe007ffffe003ffffc000ffff00003ffe000007f8000' },
  { bounds: { x: .16427432216905902, y: .7655502392344498, width: .1682615629984051, height: .16905901116427433 }, centroid: { x: .2402499195997176, y: .86141972626479 }, foregroundAreaRatio: .019187086172732105, boundingBoxAreaRatio: .028446133457465616, aspectRatio: .9952830188679245, mask: '00fe000007ffe00007fff0000ffff8000ffff8000ffff8000ffff8000ffff0000ffff0000ffff0001ffff0001ffff0001ffff0001ffff0001ffff8003ffff8003ffffc603ffffcf87ffffe7c7ffffe7e7ffffe3effffff3ffffffffffffffffffffffffffffffffffffffffffffffffefffffffe0f7ffffe003ffffc0001ffe0' },
  { bounds: { x: .3827751196172249, y: .766347687400319, width: .17065390749601275, height: .1674641148325359 }, centroid: { x: .4593750194462258, y: .8613812795752163 }, foregroundAreaRatio: .019069440310941193, boundingBoxAreaRatio: .028578405561533238, aspectRatio: 1.019047619047619, mask: '01ff000007ffe0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0000ffff0001ffff0001ffff0001ffff0001ffff0001ffff0003ffff0003ffff8607ffffc787ffffc7c7ffffe3e7ffffe3effffffbffffffffffffffffffffffffffffffffffffffffffffffffefffffffe0ffffffe003ffffc0001ffe0' },
];

const v2Slots = [slot('head', 'head', 7, v2[0]!), slot('weapon', 'weapon', 6, v2[1]!, { side: 'right' }), slot('torso', 'torso', 4, v2[2]!), slot('left-arm', 'arm', 3, v2[3]!, { side: 'left' }), slot('right-arm', 'arm', 5, v2[4]!, { side: 'right' }), slot('left-foot', 'foot', 1, v2[5]!, { side: 'left' }), slot('right-foot', 'foot', 2, v2[6]!, { side: 'right' })];
const wizardSlots = [slot('head', 'head', 8, wizard[0]!), slot('weapon', 'weapon', 7, wizard[1]!, { side: 'right' }), slot('torso', 'torso', 5, wizard[2]!), slot('right-arm', 'arm', 6, wizard[3]!, { side: 'right' }), slot('left-arm', 'arm', 4, wizard[4]!, { side: 'left' }), slot('hand', 'hand', 3, wizard[5]!, { side: 'right' }), slot('left-foot', 'foot', 1, wizard[6]!, { side: 'left' }), slot('right-foot', 'foot', 2, wizard[7]!, { side: 'right' })];

export const BUNDLED_SCHEMAS = [
  make({ schemaId: 'builtin.humanoid-wizard-v1', name: 'Humanoid Wizard Layout', slots: wizardSlots, aspectRatio: 1, foregroundBounds: { x: .05661881977671451, y: .024720893141945772, width: .8173843700159489, height: .9098883572567783 }, width: 1254, height: 1254, classes: ['builtin.character-class.wizard'] }),
  make({ schemaId: 'builtin.v2-example', name: 'V2 Example Layout', slots: v2Slots, aspectRatio: 1145 / 1374, foregroundBounds: { x: .08122270742358079, y: .11717612809315867, width: .8917030567685589, height: .7685589519650655 }, width: 1145, height: 1374, classes: ['builtin.character-class.knight'] }),
];
