/**
 * .can3 (Cubism Editor animation project) generator.
 *
 * Generates a .can3 CAFF archive containing animation data that pairs
 * with a .cmo3 model file. Animations drive ParamRotation_* parameters
 * generated by cmo3writer.js.
 *
 * The .can3 format is a CAFF archive (same container as .cmo3) with a
 * single main.xml. Structure reverse-engineered from Hiyori reference:
 *   CAnimation → CSceneSource[] → CMvTrack_Live2DModel_Source
 *     → CMvEffect_Live2DParameter → CMvAttrF[] (Bezier keyframes)
 *
 * @module io/live2d/can3writer
 */

import { packCaff, COMPRESS_FAST } from "@/io/live2d/caffPacker.js";
import { XmlBuilder, uuid } from "@/io/live2d/xmlbuilder.js";
import { expandAnimationForExport } from "@/domain/animationExportBoomerang.js";

// ---------- Processing instructions (from Hiyori can3 RE) ----------

const VERSION_PIS = [
  ["CSceneSource", "3"],
  ["CAnimation", "4"],
  ["CMvParameter_Group", "1"],
  ["SerializeFormatVersion", "2"],
  ["CMvEffect_VisualDefault", "1"],
  ["CMvMovieInfo", "3"],
  ["CBezierCtrlPt", "2"],
];

const IMPORT_PIS = [
  "com.live2d.cubism.CETargetVersion$Animation",
  "com.live2d.cubism.doc.animation.CAnimation",
  "com.live2d.cubism.doc.animation.CSceneSource",
  "com.live2d.cubism.doc.animation.formAnimation.FormAnimationSet",
  "com.live2d.cubism.doc.animation.movie.core.CMvMovieInfo",
  "com.live2d.cubism.doc.animation.movie.effect.CMvEffect_EyeBlink",
  "com.live2d.cubism.doc.animation.movie.effect.CMvEffect_LipSync",
  "com.live2d.cubism.doc.animation.movie.effect.CMvEffect_Live2DParameter",
  "com.live2d.cubism.doc.animation.movie.effect.CMvEffect_Live2DPartsVisible",
  "com.live2d.cubism.doc.animation.movie.effect.CMvEffect_VisualDefault",
  "com.live2d.cubism.doc.animation.movie.effect.CMvParameter_Group",
  "com.live2d.cubism.doc.animation.movie.effect.CSoundHandler",
  "com.live2d.cubism.doc.animation.movie.effect.CVisualHandler",
  "com.live2d.cubism.doc.animation.movie.effect.ICMvEffect",
  "com.live2d.cubism.doc.animation.movie.effect.attr.CMvAttrF",
  "com.live2d.cubism.doc.animation.movie.effect.attr.CMvAttrI",
  "com.live2d.cubism.doc.animation.movie.effect.attr.CMvAttrPt",
  "com.live2d.cubism.doc.animation.movie.effect.attr.ICMvAttr",
  "com.live2d.cubism.doc.animation.movie.effect.attr.ICMvAttr$AdaptType",
  "com.live2d.cubism.doc.animation.movie.effect.attr.value.ACValueSequence",
  "com.live2d.cubism.doc.animation.movie.effect.attr.value.CBezierCtrlPt",
  "com.live2d.cubism.doc.animation.movie.effect.attr.value.CBezierPt",
  "com.live2d.cubism.doc.animation.movie.effect.attr.value.CCurveType",
  "com.live2d.cubism.doc.animation.movie.effect.attr.value.CFixedSequence",
  "com.live2d.cubism.doc.animation.movie.effect.attr.value.CFrameIndexType",
  "com.live2d.cubism.doc.animation.movie.effect.attr.value.CIntSequence",
  "com.live2d.cubism.doc.animation.movie.effect.attr.value.CMutableSequence",
  "com.live2d.cubism.doc.animation.movie.effect.attr.value.CSeqPt",
  "com.live2d.cubism.doc.animation.movie.effect.attr.xy.CPtTNS",
  "com.live2d.cubism.doc.animation.movie.effect.attr.xy.CXY_TNSSequence",
  "com.live2d.cubism.doc.animation.movie.res.ACResourceEntry",
  "com.live2d.cubism.doc.animation.movie.res.CResourceData",
  "com.live2d.cubism.doc.animation.movie.res.CResourceGroup",
  "com.live2d.cubism.doc.animation.movie.res.CResourceManager",
  "com.live2d.cubism.doc.animation.movie.track.CMvEffectManager",
  "com.live2d.cubism.doc.animation.movie.track.CMvTrack_Group_Source",
  "com.live2d.cubism.doc.animation.movie.track.CMvTrack_Live2DModel_Source",
  "com.live2d.cubism.doc.animation.movie.track.ICMvTrack_Linked",
  "com.live2d.cubism.doc.animation.movie.track.ICMvTrack_Source",
  "com.live2d.cubism.doc.animation.movie.track.resource.ACResource_File",
  "com.live2d.cubism.doc.animation.movie.track.resource.CResource_Linked_Model",
  "com.live2d.cubism.doc.model.deformer.CTrackSourceSet",
  "com.live2d.cubism.doc.model.id.CAttrId",
  "com.live2d.cubism.doc.model.id.CEffectId",
  "com.live2d.cubism.doc.model.id.CMvParameterGroupId",
  "com.live2d.cubism.doc.model.id.CParameterId",
  "com.live2d.cubism.doc.model.id.CPartId",
  "com.live2d.cubism.doc.model.options.edition.EditorEdition",
  "com.live2d.cubism.doc.modeling.ui.viewer.sceneBlending.viewerData_SceneBlending.ASceneBlendingData",
  "com.live2d.cubism.doc.modeling.ui.viewer.sceneBlending.viewerData_SceneBlending.CSceneBlendingSettingsSource",
  "com.live2d.cubism.doc.modeling.ui.viewer.sceneBlending.viewerData_SceneBlending.PlaylistData",
  "com.live2d.cubism.doc.modeling.ui.viewer.sceneBlending.viewerData_SceneBlending.PlaylistItemData",
  "com.live2d.cubism.view.palette.scene.parameterBookmark.ParameterBookmarkLabelCarrierTrackSet",
  "com.live2d.cubism.view.palette.scene.parameterBookmark.ParameterBookmarkLabelSet",
  "com.live2d.graphics.CImageCanvas",
  "com.live2d.graphics3d.type.GRectF",
  "com.live2d.graphics3d.type.GVector2",
  "com.live2d.type.CColor",
  "com.live2d.type.CParameterGroupGuid",
  "com.live2d.type.CParameterGuid",
  "com.live2d.type.CPartGuid",
  "com.live2d.type.CPlaylistGuid",
  "com.live2d.type.CResourceGroupGuid",
  "com.live2d.type.CResourceGuid",
  "com.live2d.type.CSceneBlendingSettingsGuid",
  "com.live2d.type.CSceneGuid",
  "com.live2d.type.CTrackGuid",
];

/**
 * Generate a .can3 animation archive.
 *
 * @param {object} input
 * @param {object[]} input.animations - SS animations [{name, duration, fps, tracks}]
 * @param {Map<string, {paramId, min, max}>} input.deformerParamMap - groupId → param info
 * @param {string} input.cmo3FileName - Linked .cmo3 filename (e.g. "model.cmo3")
 * @param {number} input.canvasW
 * @param {number} input.canvasH
 * @param {string} [input.modelName]
 * @returns {Promise<Uint8Array>} .can3 CAFF archive
 */
export async function generateCan3(input) {
  const {
    animations,
    deformerParamMap,
    cmo3FileName,
    canvasW,
    canvasH,
    modelName = "Kukla2d Export",
  } = input;

  const x = new XmlBuilder();

  // Shared AdaptType for "Relative"
  const [adaptRel, pidAdaptRel] = x.shared("AdaptType");
  x.sub(adaptRel, "s", { "xs.n": "text" }).text = "Relative";

  // Shared CEffectId for Live2D parameters
  const [, pidEffIdParam] = x.shared("CEffectId", { idstr: "live2dParam" });

  // Shared CEffectId for parts visibility
  const [, pidEffIdParts] = x.shared("CEffectId", {
    idstr: "live2dPartsVisible",
  });

  // Shared CEffectId for visual default
  const [, pidEffIdVisual] = x.shared("CEffectId", { idstr: "visualDefault" });

  // Shared CTrackGuid for root track (reused across scenes per Hiyori pattern)
  const [, pidRootTrackGuid] = x.shared("CTrackGuid", {
    uuid: uuid(),
    note: "Root Track",
  });

  // Resource GUID (links to .cmo3 model)
  const [, pidResourceGuid] = x.shared("CResourceGuid", {
    uuid: uuid(),
    note: cmo3FileName,
  });

  // Parameter GUIDs — one per deformer parameter
  const paramGuids = new Map(); // paramId → pidGuid
  for (const [, info] of deformerParamMap) {
    if (!paramGuids.has(info.paramId)) {
      const [, pid] = x.shared("CParameterGuid", {
        uuid: uuid(),
        note: info.paramId,
      });
      paramGuids.set(info.paramId, pid);
    }
  }

  // Build all scenes
  const sceneRefs = [];
  const sceneGuids = [];
  const sceneAnimPlaceholders = []; // {scene, placeholder} for deferred _animation back-ref

  for (let si = 0; si < animations.length; si++) {
    const anim = expandAnimationForExport(animations[si]);
    const fps = anim.fps ?? 30;
    const durationMs = anim.duration ?? 2000;
    const durationFrames = Math.round((durationMs * fps) / 1000);
    const sceneName = (anim.name ?? `anim_${si}`).replace(
      /[^a-zA-Z0-9_-]/g,
      "_",
    );

    // Scene GUID
    const [, pidSceneGuid] = x.shared("CSceneGuid", {
      uuid: uuid(),
      note: sceneName,
    });
    sceneGuids.push(pidSceneGuid);

    // Model track GUID + allocate shared object early (filled later, pid needed by track attrs)
    const [, pidModelTrackGuid] = x.shared("CTrackGuid", {
      uuid: uuid(),
      note: `${sceneName}_model`,
    });
    const [modelTrack, pidModelTrack] = x.shared("CMvTrack_Live2DModel_Source");

    // Build CMvAttrF for each animated parameter
    const paramAttrPids = []; // pidAttrF for each parameter

    // Collect all rotation tracks for this animation
    const rotationTracks = new Map(); // groupId → track
    for (const track of anim.tracks ?? []) {
      if (
        track.property === "rotation" &&
        deformerParamMap.has(track.targetId)
      ) {
        rotationTracks.set(track.targetId, track);
      }
    }

    // Create CMvAttrF for each deformer parameter (even if no keyframes — Editor expects all)
    for (const [groupId, info] of deformerParamMap) {
      const track = rotationTracks.get(groupId);
      const [attrF, pidAttrF] = x.shared("CMvAttrF");
      paramAttrPids.push(pidAttrF);

      const attrSup = x.sub(attrF, "ICMvAttr", { "xs.n": "super" });
      x.sub(attrSup, "b", { "xs.n": "isShyMode" }).text = "false";
      x.sub(attrSup, "b", { "xs.n": "isFreezeMode" }).text = "false";
      x.sub(attrSup, "CAttrId", {
        "xs.n": "id",
        idstr: `live2dParam_${info.paramId}`,
      });
      x.sub(attrSup, "s", { "xs.n": "name" }).text = info.paramId;
      x.subRef(attrSup, "CParameterGuid", paramGuids.get(info.paramId), {
        "xs.n": "guid",
      });
      x.sub(attrSup, "b", { "xs.n": "isActive" }).text = "true";
      x.subRef(attrSup, "AdaptType", pidAdaptRel, { "xs.n": "adaptType" });
      const optParams = x.sub(attrSup, "hash_map", {
        "xs.n": "optionParam",
        count: "3",
        keyType: "string",
      });
      x.sub(optParams, "i", { "xs.n": "KEY_ATTR_FADE_OUT" }).text = "-1";
      x.sub(optParams, "i", { "xs.n": "KEY_ATTR_FADE_IN" }).text = "-1";
      x.sub(optParams, "s", { "xs.n": "KEY_PARAM_ID" }).text =
        `live2dParam:${info.paramId}`;
      // track back-reference (REQUIRED in every ICMvAttr — fixes lateinit error)
      x.subRef(attrSup, "CMvTrack_Live2DModel_Source", pidModelTrack, {
        "xs.n": "track",
      });

      // Keyframe data
      if (track && track.keyframes?.length > 0) {
        const kfs = [...track.keyframes].sort((a, b) => a.time - b.time);
        emitMutableSequence(x, attrF, pidAttrF, kfs, fps, info.min, info.max);
      } else {
        // No keyframes — emit fixed value at 0 (rest)
        emitFixedSequence(x, attrF, pidAttrF, 0);
      }

      x.sub(attrF, "d", { "xs.n": "rangeMin" }).text = String(info.min);
      x.sub(attrF, "d", { "xs.n": "rangeMax" }).text = String(info.max);
      x.sub(attrF, "b", { "xs.n": "isRepeat" }).text = "false";
      x.sub(attrF, "d", { "xs.n": "repeatMin" }).text =
        "-1.7976931348623157E308";
      x.sub(attrF, "d", { "xs.n": "repeatMax" }).text =
        "1.7976931348623157E308";
      x.sub(attrF, "null", { "xs.n": "linked_keyFormsForObject" });
    }

    // CMvEffect_Live2DParameter
    const [paramEffect, pidParamEffect] = x.shared("CMvEffect_Live2DParameter");
    const peSuper = x.sub(paramEffect, "ICMvEffect", { "xs.n": "super" });
    x.subRef(peSuper, "CEffectId", pidEffIdParam, { "xs.n": "id" });
    x.sub(peSuper, "b", { "xs.n": "isActive" }).text = "true";
    x.sub(peSuper, "b", { "xs.n": "canDelete" }).text = "false";
    const peAttrList = x.sub(peSuper, "array", {
      "xs.n": "attrList",
      count: String(paramAttrPids.length),
      type: "ICMvAttr",
    });
    for (const pid of paramAttrPids) {
      x.subRef(peAttrList, "CMvAttrF", pid);
    }
    // attrMap (hash_map: CAttrId → CMvAttrF) — INSIDE ICMvEffect super (Hiyori pattern)
    const peAttrMap = x.sub(peSuper, "hash_map", {
      "xs.n": "attrMap",
      count: String(paramAttrPids.length),
    });
    let paramIdx = 0;
    for (const [, info] of deformerParamMap) {
      const entry = x.sub(peAttrMap, "entry");
      x.sub(entry, "CAttrId", {
        "xs.n": "key",
        idstr: `live2dParam_${info.paramId}`,
      });
      x.subRef(entry, "CMvAttrF", paramAttrPids[paramIdx], { "xs.n": "value" });
      paramIdx++;
    }
    // track back-reference (REQUIRED — last child of ICMvEffect)
    x.subRef(peSuper, "CMvTrack_Live2DModel_Source", pidModelTrack, {
      "xs.n": "track",
    });
    // parameterGroupList (empty for MVP — Hiyori uses this name, not "parameterGroups")
    x.sub(paramEffect, "carray_list", {
      "xs.n": "parameterGroupList",
      count: "0",
    });

    // CMvEffect_Live2DPartsVisible (empty for MVP)
    const [partsEffect, pidPartsEffect] = x.shared(
      "CMvEffect_Live2DPartsVisible",
    );
    const pveSuper = x.sub(partsEffect, "ICMvEffect", { "xs.n": "super" });
    x.subRef(pveSuper, "CEffectId", pidEffIdParts, { "xs.n": "id" });
    x.sub(pveSuper, "b", { "xs.n": "isActive" }).text = "true";
    x.sub(pveSuper, "b", { "xs.n": "canDelete" }).text = "false";
    x.sub(pveSuper, "array", {
      "xs.n": "attrList",
      count: "0",
      type: "ICMvAttr",
    });
    x.sub(pveSuper, "hash_map", { "xs.n": "attrMap", count: "0" });
    // track back-reference (REQUIRED — last child of ICMvEffect)
    x.subRef(pveSuper, "CMvTrack_Live2DModel_Source", pidModelTrack, {
      "xs.n": "track",
    });

    // CMvEffect_VisualDefault — all 9 track transform attributes (matching Hiyori pattern)
    // Hiyori: xy, scalex, scaley, rotate, shear, anchor, opacity, frameStep, artPathWidth

    // Helper: create a CMvAttrF with CMutableSequence (Hiyori uses this even for constants)
    const makeTrackAttrF = (idstr, name, baseValue, rangeMin, rangeMax) => {
      const [attr, pid] = x.shared("CMvAttrF");
      const sup = x.sub(attr, "ICMvAttr", { "xs.n": "super" });
      x.sub(sup, "b", { "xs.n": "isShyMode" }).text = "false";
      x.sub(sup, "b", { "xs.n": "isFreezeMode" }).text = "false";
      x.sub(sup, "CAttrId", { "xs.n": "id", idstr });
      x.sub(sup, "s", { "xs.n": "name" }).text = name;
      x.sub(sup, "null", { "xs.n": "guid" });
      x.sub(sup, "b", { "xs.n": "isActive" }).text = "true";
      x.subRef(sup, "AdaptType", pidAdaptRel, { "xs.n": "adaptType" });
      x.sub(sup, "hash_map", {
        "xs.n": "optionParam",
        count: "0",
        keyType: "string",
      });
      x.subRef(sup, "CMvTrack_Live2DModel_Source", pidModelTrack, {
        "xs.n": "track",
      });
      // CMutableSequence with count=0 (Hiyori pattern for non-animated transform attrs)
      const seq = x.sub(attr, "CMutableSequence", { "xs.n": "valueData" });
      const acvs = x.sub(seq, "ACValueSequence", { "xs.n": "super" });
      x.sub(acvs, "d", { "xs.n": "curMin" }).text = String(rangeMin);
      x.sub(acvs, "d", { "xs.n": "curMax" }).text = String(rangeMax);
      x.sub(acvs, "i", { "xs.n": "posStart" }).text = "0";
      x.sub(acvs, "int-array", { "xs.n": "keyPts2", count: "0" });
      x.sub(acvs, "i", { "xs.n": "keyMin" }).text = "0";
      x.sub(acvs, "i", { "xs.n": "keyMax" }).text = "0";
      x.sub(acvs, "d", { "xs.n": "lastValue" }).text = String(baseValue);
      x.sub(acvs, "i", { "xs.n": "lastPos" }).text = "0";
      x.subRef(acvs, "CMvAttrF", pid, { "xs.n": "attr" });
      x.sub(acvs, "d", { "xs.n": "baseValue" }).text = String(baseValue);
      x.sub(seq, "array", { "xs.n": "points", count: "0", type: "CBezierPt" });
      x.sub(seq, "carray_list", { "xs.n": "curveTypes", count: "0" });
      x.sub(attr, "d", { "xs.n": "rangeMin" }).text = String(rangeMin);
      x.sub(attr, "d", { "xs.n": "rangeMax" }).text = String(rangeMax);
      x.sub(attr, "b", { "xs.n": "isRepeat" }).text = "false";
      x.sub(attr, "d", { "xs.n": "repeatMin" }).text =
        "-1.7976931348623157E308";
      x.sub(attr, "d", { "xs.n": "repeatMax" }).text = "1.7976931348623157E308";
      x.sub(attr, "null", { "xs.n": "linked_keyFormsForObject" });
      return pid;
    };

    // Helper: create a CMvAttrPt with CXY_TNSSequence (for xy and anchor)
    const makeTrackAttrPt = (idstr, name, ptX, ptY) => {
      const [attr, pid] = x.shared("CMvAttrPt");
      const sup = x.sub(attr, "ICMvAttr", { "xs.n": "super" });
      x.sub(sup, "b", { "xs.n": "isShyMode" }).text = "false";
      x.sub(sup, "b", { "xs.n": "isFreezeMode" }).text = "false";
      x.sub(sup, "CAttrId", { "xs.n": "id", idstr });
      x.sub(sup, "s", { "xs.n": "name" }).text = name;
      x.sub(sup, "null", { "xs.n": "guid" });
      x.sub(sup, "b", { "xs.n": "isActive" }).text = "true";
      x.subRef(sup, "AdaptType", pidAdaptRel, { "xs.n": "adaptType" });
      x.sub(sup, "hash_map", {
        "xs.n": "optionParam",
        count: "0",
        keyType: "string",
      });
      x.subRef(sup, "CMvTrack_Live2DModel_Source", pidModelTrack, {
        "xs.n": "track",
      });
      const seq = x.sub(attr, "CXY_TNSSequence", { "xs.n": "valueDataXY" });
      const pts = x.sub(seq, "array", {
        "xs.n": "points",
        count: "1",
        type: "CPtTNS",
      });
      const pt = x.sub(pts, "CPtTNS");
      const gv = x.sub(pt, "GVector2", { "xs.n": "super" });
      x.sub(gv, "f", { "xs.n": "x" }).text = String(ptX);
      x.sub(gv, "f", { "xs.n": "y" }).text = String(ptY);
      x.sub(pt, "b", { "xs.n": "isCorner" }).text = "false";
      const val = x.sub(pt, "GVector2", { "xs.n": "value" });
      x.sub(val, "f", { "xs.n": "x" }).text = String(ptX);
      x.sub(val, "f", { "xs.n": "y" }).text = String(ptY);
      x.sub(pt, "i", { "xs.n": "pos" }).text = "0";
      const basePt = x.sub(seq, "GVector2", { "xs.n": "basePt" });
      x.sub(basePt, "f", { "xs.n": "x" }).text = "0.0";
      x.sub(basePt, "f", { "xs.n": "y" }).text = "0.0";
      x.subRef(seq, "CMvAttrPt", pid, { "xs.n": "attr" });
      return pid;
    };

    // Helper: create a CMvAttrI with CIntSequence (for frameStep)
    const makeTrackAttrI = (idstr, name, baseValue, rangeMin, rangeMax) => {
      const [attr, pid] = x.shared("CMvAttrI");
      const sup = x.sub(attr, "ICMvAttr", { "xs.n": "super" });
      x.sub(sup, "b", { "xs.n": "isShyMode" }).text = "false";
      x.sub(sup, "b", { "xs.n": "isFreezeMode" }).text = "false";
      x.sub(sup, "CAttrId", { "xs.n": "id", idstr });
      x.sub(sup, "s", { "xs.n": "name" }).text = name;
      x.sub(sup, "null", { "xs.n": "guid" });
      x.sub(sup, "b", { "xs.n": "isActive" }).text = "true";
      x.subRef(sup, "AdaptType", pidAdaptRel, { "xs.n": "adaptType" });
      x.sub(sup, "hash_map", {
        "xs.n": "optionParam",
        count: "0",
        keyType: "string",
      });
      x.subRef(sup, "CMvTrack_Live2DModel_Source", pidModelTrack, {
        "xs.n": "track",
      });
      // CIntSequence (Hiyori pattern for frameStep)
      const seq = x.sub(attr, "CIntSequence", { "xs.n": "valueData" });
      const acvs = x.sub(seq, "ACValueSequence", { "xs.n": "super" });
      x.sub(acvs, "d", { "xs.n": "curMin" }).text = "0.0";
      x.sub(acvs, "d", { "xs.n": "curMax" }).text = "0.0";
      x.sub(acvs, "i", { "xs.n": "posStart" }).text = "0";
      x.sub(acvs, "int-array", { "xs.n": "keyPts2", count: "0" });
      x.sub(acvs, "i", { "xs.n": "keyMin" }).text = "2147483647";
      x.sub(acvs, "i", { "xs.n": "keyMax" }).text = "-2147483648";
      x.sub(acvs, "d", { "xs.n": "lastValue" }).text = "NaN";
      x.sub(acvs, "i", { "xs.n": "lastPos" }).text = "-1";
      x.subRef(acvs, "CMvAttrI", pid, { "xs.n": "attr" });
      x.sub(acvs, "d", { "xs.n": "baseValue" }).text = String(baseValue);
      x.sub(seq, "array", { "xs.n": "points", count: "0", type: "CSeqPt" });
      x.sub(attr, "i", { "xs.n": "rangeMin" }).text = String(rangeMin);
      x.sub(attr, "i", { "xs.n": "rangeMax" }).text = String(rangeMax);
      return pid;
    };

    // All 9 VisualDefault attributes (matching Hiyori exactly)
    const pidXyAttr = makeTrackAttrPt(
      "xy",
      "Position",
      canvasW / 2,
      canvasH / 2,
    );
    const pidScaleX = makeTrackAttrF(
      "scalex",
      "Scale X",
      100.0,
      -Infinity,
      Infinity,
    );
    const pidScaleY = makeTrackAttrF(
      "scaley",
      "Scale Y",
      100.0,
      -Infinity,
      Infinity,
    );
    const pidRotate = makeTrackAttrF(
      "rotate",
      "Rotation",
      0.0,
      -Infinity,
      Infinity,
    );
    const pidShear = makeTrackAttrF("shear", "Shear", 0.0, -Infinity, Infinity);
    const pidAnchorAttr = makeTrackAttrPt(
      "anchor",
      "Anchor",
      canvasW / 2,
      canvasH / 2,
    );
    const pidOpacity = makeTrackAttrF("opacity", "Opacity", 100.0, 0.0, 100.0);
    const pidFrameStep = makeTrackAttrI("frameStep", "Frame Step", 1.0, 0, 100);
    const pidArtPathWidth = makeTrackAttrF(
      "artPathWidth",
      "Art Path Width",
      100.0,
      -1.7976931348623157e308,
      1.7976931348623157e308,
    );

    // All attr pids in order (Hiyori attrList order: xy, scalex, scaley, rotate, shear, anchor, opacity, frameStep, artPathWidth)
    const veAttrPids = [
      { pid: pidXyAttr, idstr: "xy", type: "CMvAttrPt" },
      { pid: pidScaleX, idstr: "scalex", type: "CMvAttrF" },
      { pid: pidScaleY, idstr: "scaley", type: "CMvAttrF" },
      { pid: pidRotate, idstr: "rotate", type: "CMvAttrF" },
      { pid: pidShear, idstr: "shear", type: "CMvAttrF" },
      { pid: pidAnchorAttr, idstr: "anchor", type: "CMvAttrPt" },
      { pid: pidOpacity, idstr: "opacity", type: "CMvAttrF" },
      { pid: pidFrameStep, idstr: "frameStep", type: "CMvAttrI" },
      { pid: pidArtPathWidth, idstr: "artPathWidth", type: "CMvAttrF" },
    ];

    const [visualEffect, pidVisualEffect] = x.shared("CMvEffect_VisualDefault");
    const veSuper = x.sub(visualEffect, "ICMvEffect", { "xs.n": "super" });
    x.subRef(veSuper, "CEffectId", pidEffIdVisual, { "xs.n": "id" });
    x.sub(veSuper, "b", { "xs.n": "isActive" }).text = "true";
    x.sub(veSuper, "b", { "xs.n": "canDelete" }).text = "false";
    // attrList (all 9 attrs)
    const veAttrList = x.sub(veSuper, "array", {
      "xs.n": "attrList",
      count: "9",
      type: "ICMvAttr",
    });
    for (const a of veAttrPids) x.subRef(veAttrList, a.type, a.pid);
    // attrMap — INSIDE ICMvEffect super (Hiyori pattern)
    const veAttrMap = x.sub(veSuper, "hash_map", {
      "xs.n": "attrMap",
      count: "9",
    });
    for (const a of veAttrPids) {
      const e = x.sub(veAttrMap, "entry");
      x.sub(e, "CAttrId", { "xs.n": "key", idstr: a.idstr });
      x.subRef(e, a.type, a.pid, { "xs.n": "value" });
    }
    // track back-reference (REQUIRED — last child of ICMvEffect)
    x.subRef(veSuper, "CMvTrack_Live2DModel_Source", pidModelTrack, {
      "xs.n": "track",
    });
    // Named attribute fields — CMvEffect_VisualDefault.deserialize() expects these!
    x.subRef(visualEffect, "CMvAttrPt", pidXyAttr, { "xs.n": "attrXY" });
    x.subRef(visualEffect, "CMvAttrF", pidScaleX, { "xs.n": "attrScaleX" });
    x.subRef(visualEffect, "CMvAttrF", pidScaleY, { "xs.n": "attrScaleY" });
    x.subRef(visualEffect, "CMvAttrF", pidRotate, { "xs.n": "attrRotate" });
    x.subRef(visualEffect, "CMvAttrPt", pidAnchorAttr, {
      "xs.n": "attrAnchorXY",
    });
    x.subRef(visualEffect, "CMvAttrF", pidShear, { "xs.n": "attrShear" });
    x.subRef(visualEffect, "CMvAttrF", pidOpacity, { "xs.n": "attrOpacity" });
    x.subRef(visualEffect, "CMvAttrI", pidFrameStep, {
      "xs.n": "attrFrameStep",
    });
    x.subRef(visualEffect, "CMvAttrF", pidArtPathWidth, {
      "xs.n": "attrArtPathWidth",
    });

    // CMvEffect_EyeBlink (empty stub with required fields — Hiyori pattern)
    const [eyeBlinkEffect, pidEyeBlink] = x.shared("CMvEffect_EyeBlink");
    const ebSuper = x.sub(eyeBlinkEffect, "ICMvEffect", { "xs.n": "super" });
    x.sub(ebSuper, "CEffectId", { "xs.n": "id", idstr: "eyeBlink" });
    x.sub(ebSuper, "b", { "xs.n": "isActive" }).text = "false";
    x.sub(ebSuper, "b", { "xs.n": "canDelete" }).text = "true";
    x.sub(ebSuper, "array", {
      "xs.n": "attrList",
      count: "0",
      type: "ICMvAttr",
    });
    x.sub(ebSuper, "hash_map", { "xs.n": "attrMap", count: "0" });
    x.subRef(ebSuper, "CMvTrack_Live2DModel_Source", pidModelTrack, {
      "xs.n": "track",
    });
    // EyeBlink-specific fields (Hiyori pattern)
    x.sub(eyeBlinkEffect, "carray_list", {
      "xs.n": "effectParameterAttrIds",
      count: "0",
    });
    x.sub(eyeBlinkEffect, "b", { "xs.n": "invert" }).text = "false";
    x.sub(eyeBlinkEffect, "b", { "xs.n": "relative" }).text = "true";

    // CMvEffect_LipSync (empty stub with required fields — Hiyori pattern)
    const [lipSyncEffect, pidLipSync] = x.shared("CMvEffect_LipSync");
    const lsSuper = x.sub(lipSyncEffect, "ICMvEffect", { "xs.n": "super" });
    x.sub(lsSuper, "CEffectId", { "xs.n": "id", idstr: "lipSync" });
    x.sub(lsSuper, "b", { "xs.n": "isActive" }).text = "false";
    x.sub(lsSuper, "b", { "xs.n": "canDelete" }).text = "true";
    x.sub(lsSuper, "array", {
      "xs.n": "attrList",
      count: "0",
      type: "ICMvAttr",
    });
    x.sub(lsSuper, "hash_map", { "xs.n": "attrMap", count: "0" });
    x.subRef(lsSuper, "CMvTrack_Live2DModel_Source", pidModelTrack, {
      "xs.n": "track",
    });
    // LipSync-specific fields (Hiyori pattern)
    x.sub(lipSyncEffect, "carray_list", {
      "xs.n": "effectParameterAttrIds",
      count: "0",
    });
    x.sub(lipSyncEffect, "null", { "xs.n": "syncTrackGuid" });
    x.sub(lipSyncEffect, "b", { "xs.n": "isInvert" }).text = "false";
    x.sub(lipSyncEffect, "b", { "xs.n": "isRelative" }).text = "true";

    // CMvTrack_Group_Source (Root track)
    const [rootTrack, pidRootTrack] = x.shared("CMvTrack_Group_Source");
    const rtSup = x.sub(rootTrack, "ICMvTrack_Source", { "xs.n": "super" });
    x.sub(rtSup, "s", { "xs.n": "name" }).text = "Root";
    x.sub(rtSup, "b", { "xs.n": "isUserRenamed" }).text = "false";
    x.subRef(rtSup, "CTrackGuid", pidRootTrackGuid, { "xs.n": "guid" });
    x.sub(rtSup, "i", { "xs.n": "start" }).text = "0";
    x.sub(rtSup, "i", { "xs.n": "internalOffset" }).text = "0";
    x.sub(rtSup, "i", { "xs.n": "duration" }).text = String(durationFrames);
    x.sub(rtSup, "b", { "xs.n": "editable" }).text = "true";
    x.sub(rtSup, "b", { "xs.n": "visible" }).text = "true";
    x.sub(rtSup, "b", { "xs.n": "mute" }).text = "false";
    x.sub(rtSup, "b", { "xs.n": "isGuide" }).text = "false";
    x.sub(rtSup, "b", { "xs.n": "isRepeat" }).text = "false";
    x.sub(rtSup, "b", { "xs.n": "soloSwitch" }).text = "false";
    const rtVis = x.sub(rtSup, "CVisualHandler", { "xs.n": "visualHandler" });
    x.subRef(rtVis, "CMvTrack_Group_Source", pidRootTrack, { "xs.n": "track" });
    const rtSnd = x.sub(rtSup, "CSoundHandler", { "xs.n": "soundHandler" });
    x.subRef(rtSnd, "CMvTrack_Group_Source", pidRootTrack, { "xs.n": "track" });
    x.sub(rtSup, "null", { "xs.n": "soundEffect" });
    x.sub(rtSup, "null", { "xs.n": "visualEffect" });
    const rtEffMgr = x.sub(rtSup, "CMvEffectManager", {
      "xs.n": "effectManager",
    });
    x.sub(rtEffMgr, "array", {
      "xs.n": "effectList",
      count: "0",
      type: "ICMvEffect",
    });
    x.sub(rtSup, "null", { "xs.n": "parentGuid" });
    // _sceneSource filled below
    x.sub(rtSup, "hash_map", {
      "xs.n": "userData",
      count: "0",
      keyType: "string",
    });
    x.sub(rtSup, "null", { "xs.n": "keys" });
    const rtChildren = x.sub(rootTrack, "carray_list", {
      "xs.n": "_childTrackGuids",
      count: "1",
    });
    x.subRef(rtChildren, "CTrackGuid", pidModelTrackGuid);
    const rtBounds = x.sub(rootTrack, "GRectF", { "xs.n": "bounds" });
    x.sub(rtBounds, "f", { "xs.n": "x" }).text = "0.0";
    x.sub(rtBounds, "f", { "xs.n": "y" }).text = "0.0";
    x.sub(rtBounds, "f", { "xs.n": "width" }).text = "640.0";
    x.sub(rtBounds, "f", { "xs.n": "height" }).text = "480.0";

    // CMvTrack_Live2DModel_Source (model track — allocated earlier, filled here)
    const mtLinked = x.sub(modelTrack, "ICMvTrack_Linked", { "xs.n": "super" });
    const mtSup = x.sub(mtLinked, "ICMvTrack_Source", { "xs.n": "super" });
    x.sub(mtSup, "s", { "xs.n": "name" }).text = modelName;
    x.sub(mtSup, "b", { "xs.n": "isUserRenamed" }).text = "true";
    x.subRef(mtSup, "CTrackGuid", pidModelTrackGuid, { "xs.n": "guid" });
    x.sub(mtSup, "i", { "xs.n": "start" }).text = "0";
    x.sub(mtSup, "i", { "xs.n": "internalOffset" }).text = "0";
    x.sub(mtSup, "i", { "xs.n": "duration" }).text = String(durationFrames);
    x.sub(mtSup, "b", { "xs.n": "editable" }).text = "true";
    x.sub(mtSup, "b", { "xs.n": "visible" }).text = "true";
    x.sub(mtSup, "b", { "xs.n": "mute" }).text = "false";
    x.sub(mtSup, "b", { "xs.n": "isGuide" }).text = "false";
    x.sub(mtSup, "b", { "xs.n": "isRepeat" }).text = "false";
    x.sub(mtSup, "b", { "xs.n": "soloSwitch" }).text = "false";
    const mtVis = x.sub(mtSup, "CVisualHandler", { "xs.n": "visualHandler" });
    x.subRef(mtVis, "CMvTrack_Live2DModel_Source", pidModelTrack, {
      "xs.n": "track",
    });
    const mtSnd = x.sub(mtSup, "CSoundHandler", { "xs.n": "soundHandler" });
    x.subRef(mtSnd, "CMvTrack_Live2DModel_Source", pidModelTrack, {
      "xs.n": "track",
    });
    x.sub(mtSup, "null", { "xs.n": "soundEffect" });
    x.subRef(mtSup, "CMvEffect_VisualDefault", pidVisualEffect, {
      "xs.n": "visualEffect",
    });
    const mtEffMgr = x.sub(mtSup, "CMvEffectManager", {
      "xs.n": "effectManager",
    });
    const mtEffList = x.sub(mtEffMgr, "array", {
      "xs.n": "effectList",
      count: "5",
      type: "ICMvEffect",
    });
    x.subRef(mtEffList, "CMvEffect_EyeBlink", pidEyeBlink);
    x.subRef(mtEffList, "CMvEffect_LipSync", pidLipSync);
    x.subRef(mtEffList, "CMvEffect_Live2DParameter", pidParamEffect);
    x.subRef(mtEffList, "CMvEffect_Live2DPartsVisible", pidPartsEffect);
    x.subRef(mtEffList, "CMvEffect_VisualDefault", pidVisualEffect);
    x.subRef(mtSup, "CTrackGuid", pidRootTrackGuid, { "xs.n": "parentGuid" });
    x.sub(mtSup, "hash_map", {
      "xs.n": "userData",
      count: "0",
      keyType: "string",
    });
    x.sub(mtSup, "null", { "xs.n": "keys" });
    x.subRef(mtLinked, "CResourceGuid", pidResourceGuid, {
      "xs.n": "_resourceGuid",
    });
    x.subRef(modelTrack, "CMvEffect_Live2DParameter", pidParamEffect, {
      "xs.n": "keyParamEffect",
    });
    x.subRef(modelTrack, "CMvEffect_Live2DPartsVisible", pidPartsEffect, {
      "xs.n": "partsVisibleEffect",
    });
    x.subRef(modelTrack, "CMvEffect_LipSync", pidLipSync, {
      "xs.n": "lipSyncEffect",
    });
    x.subRef(modelTrack, "CMvEffect_EyeBlink", pidEyeBlink, {
      "xs.n": "eyeBlinkEffect",
    });
    x.sub(modelTrack, "null", { "xs.n": "formEditEffect" });
    const fAnimSet = x.sub(modelTrack, "FormAnimationSet", {
      "xs.n": "formAnimationSet",
    });
    x.sub(fAnimSet, "hash_map", {
      "xs.n": "formMapOnGlobal",
      count: "0",
      keyType: "string",
    });
    x.sub(fAnimSet, "hash_map", {
      "xs.n": "formMapOnLocal",
      count: "0",
      keyType: "string",
    });
    x.subRef(fAnimSet, "CMvTrack_Live2DModel_Source", pidModelTrack, {
      "xs.n": "trackSource",
    });
    const mtBounds = x.sub(modelTrack, "GRectF", { "xs.n": "bounds" });
    x.sub(mtBounds, "f", { "xs.n": "x" }).text = "0.0";
    x.sub(mtBounds, "f", { "xs.n": "y" }).text = "0.0";
    x.sub(mtBounds, "f", { "xs.n": "width" }).text = String(canvasW) + ".0";
    x.sub(mtBounds, "f", { "xs.n": "height" }).text = String(canvasH) + ".0";
    const pbSet = x.sub(modelTrack, "ParameterBookmarkLabelSet", {
      "xs.n": "parameterBookmarkLabelSet",
    });
    x.sub(pbSet, "carray_list", { "xs.n": "labels", count: "0" });

    // Back-reference: root track → scene source (need scene pid, created below)
    // We'll set this via a deferred approach

    // CSceneSource
    const [scene, pidScene] = x.shared("CSceneSource", {
      exportMotionFile: "true",
    });
    sceneRefs.push(pidScene);
    // animPlaceholder declared below, pushed after creation

    x.sub(scene, "s", { "xs.n": "sceneName" }).text = sceneName;
    const scCanvas = x.sub(scene, "CImageCanvas", { "xs.n": "canvas" });
    x.sub(scCanvas, "i", { "xs.n": "pixelWidth" }).text = String(canvasW);
    x.sub(scCanvas, "i", { "xs.n": "pixelHeight" }).text = String(canvasH);
    x.sub(scCanvas, "CColor", { "xs.n": "background" });
    x.subRef(scene, "CSceneGuid", pidSceneGuid, { "xs.n": "guid" });
    x.sub(scene, "s", { "xs.n": "tag" }).text = "";
    const trackSourceSet = x.sub(scene, "CTrackSourceSet", {
      "xs.n": "trackSourceSet",
    });
    const tsSources = x.sub(trackSourceSet, "carray_list", {
      "xs.n": "_sources",
      count: "2",
    });
    x.subRef(tsSources, "CMvTrack_Group_Source", pidRootTrack);
    x.subRef(tsSources, "CMvTrack_Live2DModel_Source", pidModelTrack);
    x.subRef(scene, "CMvTrack_Group_Source", pidRootTrack, {
      "xs.n": "rootTrack",
    });

    const movieInfo = x.sub(scene, "CMvMovieInfo", { "xs.n": "movieInfo" });
    x.sub(movieInfo, "i", { "xs.n": "width" }).text = "320";
    x.sub(movieInfo, "i", { "xs.n": "height" }).text = "240";
    x.sub(movieInfo, "i", { "xs.n": "duration" }).text = String(durationFrames);
    x.sub(movieInfo, "d", { "xs.n": "fps" }).text = String(fps) + ".0";
    x.sub(movieInfo, "i", { "xs.n": "workspaceStart" }).text = "0";
    x.sub(movieInfo, "i", { "xs.n": "workspaceEnd" }).text = String(
      durationFrames - 1,
    );
    x.sub(movieInfo, "CColor", { "xs.n": "background" });
    x.sub(movieInfo, "i", { "xs.n": "fadeInMSec" }).text = "-1";
    x.sub(movieInfo, "i", { "xs.n": "fadeOutMSec" }).text = "-1";
    x.sub(movieInfo, "b", { "xs.n": "isBezierRestricted" }).text = "false";
    x.sub(movieInfo, "b", { "xs.n": "isLoopMotion" }).text = "false";
    x.sub(movieInfo, "i", { "xs.n": "startFrame" }).text = "0";
    x.sub(movieInfo, "CFrameIndexType", {
      "xs.n": "frameIndexType",
      v: "ZERO_INDEX",
    });

    // _animation placeholder — replaced with CAnimation ref after it's created
    const animPlaceholder = x.sub(scene, "null", { "xs.n": "_animation" });
    sceneAnimPlaceholders.push({ scene, placeholder: animPlaceholder });
    x.sub(scene, "hash_map", {
      "xs.n": "marker",
      count: "0",
      keyType: "string",
    });
    x.sub(scene, "CCurveType", {
      "xs.n": "defaultParameterCurveType",
      v: "SMOOTH",
    });
    x.sub(scene, "CCurveType", { "xs.n": "defaultPartCurveType", v: "STEP" });
    x.sub(scene, "b", { "xs.n": "fixAspect" }).text = "true";
    x.sub(scene, "Animation", { "xs.n": "targetVersion", v: "FOR_SDK" });
    x.sub(scene, "b", { "xs.n": "lockMarker" }).text = "false";
    x.sub(scene, "array_list", { "xs.n": "onionSkinMarker", count: "0" });
    x.sub(scene, "b", { "xs.n": "lockOnionSkinMarker" }).text = "false";
    const pbcTrackSet = x.sub(scene, "ParameterBookmarkLabelCarrierTrackSet", {
      "xs.n": "parameterBookmarkCarrierTrackSet",
    });
    x.subRef(pbcTrackSet, "CSceneSource", pidScene, { "xs.n": "_owner" });
    x.sub(pbcTrackSet, "carray_list", { "xs.n": "_trackSortInfo", count: "0" });

    // Set root track's _sceneSource reference
    x.subRef(rtSup, "CSceneSource", pidScene, { "xs.n": "_sceneSource" });
    // Set model track's _sceneSource
    x.subRef(mtSup, "CSceneSource", pidScene, { "xs.n": "_sceneSource" });
  }

  // CResourceManager
  const [resMgr, pidResMgr] = x.shared("CResourceManager");
  const [, pidResGroupGuid] = x.shared("CResourceGroupGuid", {
    uuid: uuid(),
    note: "Root Resource Group",
  });
  const resGroup = x.sub(resMgr, "CResourceGroup", { "xs.n": "rootGroup" });
  const resGroupSup = x.sub(resGroup, "ACResourceEntry", { "xs.n": "super" });
  x.sub(resGroupSup, "null", { "xs.n": "parentGuid" });
  x.subRef(resGroupSup, "CResourceManager", pidResMgr, {
    "xs.n": "_resourceManager",
  });
  x.subRef(resGroup, "CResourceGroupGuid", pidResGroupGuid, { "xs.n": "guid" });
  const resChildren = x.sub(resGroup, "carray_list", {
    "xs.n": "_childGuids",
    count: "1",
  });
  x.subRef(resChildren, "CResourceGuid", pidResourceGuid);
  x.sub(resGroup, "s", { "xs.n": "name" }).text = "Resources";

  const resRefList = x.sub(resMgr, "carray_list", {
    "xs.n": "_resourceRefList",
    count: "1",
  });
  const [resData, pidResData] = x.shared("CResourceData");
  x.subRef(resRefList, "CResourceData", pidResData);
  const resDataSup = x.sub(resData, "ACResourceEntry", { "xs.n": "super" });
  x.subRef(resDataSup, "CResourceGroupGuid", pidResGroupGuid, {
    "xs.n": "parentGuid",
  });
  x.subRef(resDataSup, "CResourceManager", pidResMgr, {
    "xs.n": "_resourceManager",
  });
  x.sub(resData, "null", { "xs.n": "customName" });
  const resRef = x.sub(resData, "CResource_Linked_Model", {
    "xs.n": "resourceRef",
  });
  const resFile = x.sub(resRef, "ACResource_File", { "xs.n": "super" });
  x.sub(resFile, "file", { "xs.n": "srcFile" }).text = cmo3FileName;
  x.subRef(resFile, "CResourceGuid", pidResourceGuid, { "xs.n": "guid" });
  x.sub(resFile, "s", { "xs.n": "name" }).text = cmo3FileName;

  const resGuidMap = x.sub(resMgr, "hash_map", {
    "xs.n": "resourceGuidMap",
    count: "1",
  });
  const rgmEntry = x.sub(resGuidMap, "entry");
  x.subRef(rgmEntry, "CResourceGuid", pidResourceGuid, { "xs.n": "key" });
  x.subRef(rgmEntry, "CResourceData", pidResData, { "xs.n": "value" });
  x.sub(resMgr, "carray_list", { "xs.n": "_resourceGroupList", count: "0" });
  x.sub(resMgr, "hash_map", {
    "xs.n": "resourceGroupGuidMap",
    count: "0",
    keyType: "string",
  });
  // Link to last scene
  if (sceneRefs.length > 0) {
    x.subRef(resMgr, "CSceneSource", sceneRefs[sceneRefs.length - 1], {
      "xs.n": "_sceneSource",
    });
  }

  // ==================================================================
  // CAnimation (SHARED — main section references it, matching Hiyori pattern)
  // ==================================================================

  const [animation, pidAnimation] = x.shared("CAnimation");
  x.sub(animation, "s", { "xs.n": "name" }).text = modelName;
  x.sub(animation, "file", { "xs.n": "file" }).text = `${modelName}.can3`;
  const scenesArr = x.sub(animation, "carray_list", {
    "xs.n": "_scenes",
    count: String(sceneRefs.length),
  });
  for (const pid of sceneRefs) {
    x.subRef(scenesArr, "CSceneSource", pid);
  }
  if (sceneRefs.length > 0) {
    x.subRef(animation, "CSceneSource", sceneRefs[0], {
      "xs.n": "currentScene",
    });
  }
  x.subRef(animation, "CResourceManager", pidResMgr, {
    "xs.n": "resourceManager",
  });
  const edEdition = x.sub(animation, "EditorEdition", {
    "xs.n": "editorEdition",
  });
  x.sub(edEdition, "i", { "xs.n": "edition" }).text = "15";

  // Scene blending settings
  const sbs = x.sub(animation, "CSceneBlendingSettingsSource", {
    "xs.n": "sceneBlendingSettings",
  });
  x.sub(sbs, "CSceneBlendingSettingsGuid", {
    "xs.n": "guid",
    uuid: uuid(),
    note: "(no debug info)",
  });
  const playlists = x.sub(sbs, "carray_list", {
    "xs.n": "playlists",
    count: "1",
  });
  const playlist = x.sub(playlists, "PlaylistData");
  x.sub(playlist, "CPlaylistGuid", {
    "xs.n": "guid",
    uuid: uuid(),
    note: "(no debug info)",
  });
  x.sub(playlist, "s", { "xs.n": "name" }).text = "default";
  const plItems = x.sub(playlist, "carray_list", {
    "xs.n": "list",
    count: String(sceneGuids.length),
  });
  for (const gid of sceneGuids) {
    const item = x.sub(plItems, "PlaylistItemData");
    x.sub(item, "ASceneBlendingData", { "xs.n": "super" });
    x.subRef(item, "CSceneGuid", gid, { "xs.n": "guid" });
  }
  x.sub(sbs, "carray_list", { "xs.n": "sceneGroups", count: "0" });

  x.sub(animation, "b", { "xs.n": "hideAbsolutePathIfLinkError" }).text =
    "false";
  x.sub(animation, "Animation", { "xs.n": "targetVersion", v: "FOR_SDK" });
  x.sub(animation, "b", { "xs.n": "isSmoothCurveLegacyMode" }).text = "true";

  // Back-reference: replace _animation placeholders with CAnimation ref
  for (const { scene, placeholder } of sceneAnimPlaceholders) {
    const idx = scene.children.indexOf(placeholder);
    if (idx >= 0) {
      scene.children[idx] = x.ref("CAnimation", pidAnimation, {
        "xs.n": "_animation",
      });
    }
  }

  // ==================================================================
  // BUILD main.xml
  // ==================================================================

  const root = x.el("root", { fileFormatVersion: "402030000" });

  const sharedElem = x.sub(root, "shared");
  for (const obj of x._shared) {
    sharedElem.children.push(obj);
  }

  // Main section: just a reference to the shared CAnimation (Hiyori pattern)
  const mainElem = x.sub(root, "main");
  x.subRef(mainElem, "CAnimation", pidAnimation);

  // ==================================================================
  // SERIALIZE + PACK INTO CAFF
  // ==================================================================

  const xmlStr = x.serialize(root, VERSION_PIS, IMPORT_PIS);
  const xmlBytes = new TextEncoder().encode(xmlStr);

  const caffFiles = [
    {
      path: "main.xml",
      content: xmlBytes,
      tag: "main_xml",
      obfuscated: true,
      compress: COMPRESS_FAST,
    },
  ];

  return packCaff(caffFiles, 42);
}

// ---------- Keyframe helpers ----------

/**
 * Emit a CMutableSequence with Bezier keyframes.
 * SS keyframes are {time: ms, value: number, easing: string}.
 * Can3 uses frame-based positions with CBezierPt.
 */
function emitMutableSequence(
  x,
  parent,
  pidAttr,
  keyframes,
  fps,
  _rangeMin,
  _rangeMax,
) {
  const seq = x.sub(parent, "CMutableSequence", { "xs.n": "valueData" });
  const acvs = x.sub(seq, "ACValueSequence", { "xs.n": "super" });

  // Convert keyframes to frame positions
  const frameKfs = keyframes.map((kf) => ({
    frame: Math.round((kf.time * fps) / 1000),
    value: kf.value ?? 0,
  }));

  const values = frameKfs.map((k) => k.value);
  const curMin = Math.min(...values);
  const curMax = Math.max(...values);

  x.sub(acvs, "d", { "xs.n": "curMin" }).text = String(curMin);
  x.sub(acvs, "d", { "xs.n": "curMax" }).text = String(curMax);
  x.sub(acvs, "i", { "xs.n": "posStart" }).text = "0";
  x.sub(acvs, "int-array", {
    "xs.n": "keyPts2",
    count: String(frameKfs.length),
  }).text = frameKfs.map((k) => String(k.frame)).join(" ");
  x.sub(acvs, "i", { "xs.n": "keyMin" }).text = String(frameKfs[0].frame);
  x.sub(acvs, "i", { "xs.n": "keyMax" }).text = String(
    frameKfs[frameKfs.length - 1].frame,
  );
  x.sub(acvs, "d", { "xs.n": "lastValue" }).text = String(frameKfs[0].value);
  x.sub(acvs, "i", { "xs.n": "lastPos" }).text = "0";
  x.subRef(acvs, "CMvAttrF", pidAttr, { "xs.n": "attr" });
  x.sub(acvs, "d", { "xs.n": "baseValue" }).text = "0.0";

  // Bezier points
  const pts = x.sub(seq, "array", {
    "xs.n": "points",
    count: String(frameKfs.length),
    type: "CBezierPt",
  });

  for (let i = 0; i < frameKfs.length; i++) {
    const kf = frameKfs[i];
    const bp = x.sub(pts, "CBezierPt");

    // Anchor
    const anchor = x.sub(bp, "CSeqPt", { "xs.n": "anchor" });
    x.sub(anchor, "b", { "xs.n": "isCorner" }).text = "false";
    x.sub(anchor, "i", { "xs.n": "pos" }).text = String(kf.frame);
    x.sub(anchor, "d", { "xs.n": "doubleValue" }).text = String(kf.value);

    // Next control point (cubic bezier handle)
    const nextCtrl = x.sub(bp, "CBezierCtrlPt", { "xs.n": "next" });
    const nextFrame =
      i < frameKfs.length - 1
        ? kf.frame + (frameKfs[i + 1].frame - kf.frame) / 3
        : kf.frame;
    x.sub(nextCtrl, "f", { "xs.n": "posF" }).text = nextFrame.toFixed(6);
    x.sub(nextCtrl, "i", { "xs.n": "pos" }).text = "0";
    x.sub(nextCtrl, "d", { "xs.n": "doubleValue" }).text = String(kf.value);
    x.sub(nextCtrl, "b", { "xs.n": "isPosOptimized" }).text = "false";

    // Prev control point
    const prevCtrl = x.sub(bp, "CBezierCtrlPt", { "xs.n": "prev" });
    const prevFrame =
      i > 0 ? kf.frame - (kf.frame - frameKfs[i - 1].frame) / 3 : kf.frame;
    x.sub(prevCtrl, "f", { "xs.n": "posF" }).text = prevFrame.toFixed(6);
    x.sub(prevCtrl, "i", { "xs.n": "pos" }).text = "0";
    x.sub(prevCtrl, "d", { "xs.n": "doubleValue" }).text = String(kf.value);
    x.sub(prevCtrl, "b", { "xs.n": "isPosOptimized" }).text = "false";
  }

  // Curve types (one per keyframe)
  const ctList = x.sub(seq, "carray_list", {
    "xs.n": "curveTypes",
    count: String(frameKfs.length),
  });
  for (let i = 0; i < frameKfs.length; i++) {
    x.sub(ctList, "CCurveType", { v: "SMOOTH" });
  }
}

/**
 * Emit a CFixedSequence (single constant value, no keyframes).
 * CFixedSequence is NOT a subclass of ACValueSequence — it only has a value field.
 */
function emitFixedSequence(x, parent, pidAttr, value) {
  const seq = x.sub(parent, "CFixedSequence", { "xs.n": "valueData" });
  x.sub(seq, "d", { "xs.n": "value" }).text = String(value);
}
