import { clampBp, distanceScore, iou, maskSimilarity, ratioScore } from '../scoring/math.js';

import type { AnalyzerResult, ComparisonAnalyzer, ComparisonContext, MetricCheck, ObservedComponent, SchemaSlot } from '../contracts/index.js';

const result = (id: string, context: ComparisonContext, checks: MetricCheck[], diagnostics: AnalyzerResult['diagnostics'] = []): AnalyzerResult => {
  const weightBp = context.schema.matcherProfile.analyzerWeightsBp[id] ?? 0;
  if (!checks.length) return { analyzerId: id, analyzerVersion: 1, status: 'not-applicable', scoreBp: 0, passed: false, weightBp, checks, diagnostics };
  const scoreBp = Math.round(checks.reduce((sum, check) => sum + check.scoreBp, 0) / checks.length);
  return { analyzerId: id, analyzerVersion: 1, status: 'scored', scoreBp, passed: scoreBp >= context.schema.matcherProfile.passThresholdBp, weightBp, checks, diagnostics };
};
const assignmentFor = (context: ComparisonContext, key: string) => context.assignments.find(item => item.slotKey === key);
const actualsFor = (context: ComparisonContext, key: string) => (assignmentFor(context, key)?.componentIds ?? []).map(id => context.observation.components.find(item => item.componentId === id)).filter((item): item is ObservedComponent => !!item);
const expectedUnion = (slot: SchemaSlot) => slot.components.length ? { x: Math.min(...slot.components.map(c => c.bounds.x)), y: Math.min(...slot.components.map(c => c.bounds.y)), width: Math.max(...slot.components.map(c => c.bounds.x + c.bounds.width)) - Math.min(...slot.components.map(c => c.bounds.x)), height: Math.max(...slot.components.map(c => c.bounds.y + c.bounds.height)) - Math.min(...slot.components.map(c => c.bounds.y)) } : null;
const actualUnion = (items: ObservedComponent[]) => items.length ? { x: Math.min(...items.map(c => c.bounds.x)), y: Math.min(...items.map(c => c.bounds.y)), width: Math.max(...items.map(c => c.bounds.x + c.bounds.width)) - Math.min(...items.map(c => c.bounds.x)), height: Math.max(...items.map(c => c.bounds.y + c.bounds.height)) - Math.min(...items.map(c => c.bounds.y)) } : null;
const metric = (items: ObservedComponent[], kind: 'foreground-area' | 'bounds-area' | 'width' | 'height'): number => { const bounds = actualUnion(items); if (kind === 'foreground-area') return items.reduce((sum, item) => sum + item.foregroundAreaRatio, 0); if (kind === 'bounds-area') return bounds ? bounds.width * bounds.height : 0; return bounds?.[kind] ?? 0; };
const expectedMetric = (slot: SchemaSlot | undefined, kind: 'foreground-area' | 'bounds-area' | 'width' | 'height'): number => {
  if (!slot) return 0;
  const bounds = expectedUnion(slot);
  if (kind === 'foreground-area') return slot.components.reduce((sum, item) => sum + item.foregroundAreaRatio, 0);
  if (kind === 'bounds-area') return bounds ? bounds.width * bounds.height : 0;
  return bounds?.[kind] ?? 0;
};

export const analyzers: readonly ComparisonAnalyzer[] = [
  { id: 'canvas.aspect-ratio', version: 1, phase: 'global', analyze: (c: ComparisonContext, r): AnalyzerResult => result('canvas.aspect-ratio', c, [{ id: 'canvas', label: 'Canvas aspect ratio', expected: c.schema.fingerprint.canvasAspectRatio, actual: c.observation.canvas.aspectRatio, tolerance: r.profile.aspectRatioTolerance, scoreBp: ratioScore(c.observation.canvas.aspectRatio, c.schema.fingerprint.canvasAspectRatio, r.profile.aspectRatioTolerance), passed: ratioScore(c.observation.canvas.aspectRatio, c.schema.fingerprint.canvasAspectRatio, r.profile.aspectRatioTolerance) >= r.profile.passThresholdBp }]) },
  { id: 'islands.count', version: 1, phase: 'global', analyze: (c: ComparisonContext): AnalyzerResult => { const expected = c.schema.fingerprint.expectedIslandCount; const actual = c.observation.components.length; const scoreBp = clampBp(10000 * Math.min(expected, actual) / Math.max(expected, actual, 1)); return result('islands.count', c, [{ id: 'count', label: 'Island count', expected, actual, scoreBp, passed: expected === actual }]); } },
  { id: 'parts.component-count', version: 1, phase: 'assignment', analyze: c => result('parts.component-count', c, c.schema.slots.map(slot => { const expected = slot.components.length; const actual = actualsFor(c, slot.slotKey).length; const scoreBp = clampBp(10000 * Math.min(expected, actual) / Math.max(expected, actual, 1)); return { id: slot.slotKey, label: `${slot.label} component count`, expected, actual, scoreBp, passed: expected === actual }; })) },
  { id: 'parts.position', version: 1, phase: 'assignment', analyze: (c, r) => result('parts.position', c, c.schema.slots.flatMap(slot => actualsFor(c, slot.slotKey).map((actual, index) => { const expected = slot.components[index]; const distance = expected ? Math.hypot(actual.centroid.x - expected.centroid.x, actual.centroid.y - expected.centroid.y) : 1; const scoreBp = distanceScore(distance, r.profile.positionTolerance); return { id: `${slot.slotKey}.${index}`, label: `${slot.label} position`, expected: expected?.centroid ?? 'missing', actual: actual.centroid, tolerance: r.profile.positionTolerance, scoreBp, passed: scoreBp >= r.profile.passThresholdBp }; }))) },
  { id: 'parts.bounds-overlap', version: 1, phase: 'assignment', analyze: c => result('parts.bounds-overlap', c, c.schema.slots.flatMap(slot => { const expected = expectedUnion(slot); const actual = actualUnion(actualsFor(c, slot.slotKey)); if (!expected || !actual) return []; const scoreBp = clampBp(iou(actual, expected) * 10000); return [{ id: slot.slotKey, label: `${slot.label} bounds`, expected, actual, scoreBp, passed: scoreBp >= c.schema.matcherProfile.passThresholdBp }]; })) },
  { id: 'parts.absolute-size', version: 1, phase: 'assignment', analyze: (c, r) => result('parts.absolute-size', c, c.schema.slots.flatMap(slot => { const actual = actualsFor(c, slot.slotKey); if (!actual.length) return []; const expected = slot.components.reduce((sum, item) => sum + item.foregroundAreaRatio, 0); const measured = metric(actual, 'foreground-area'); const scoreBp = ratioScore(measured, expected, r.profile.sizeTolerance); return [{ id: slot.slotKey, label: `${slot.label} area`, expected, actual: measured, tolerance: r.profile.sizeTolerance, scoreBp, passed: scoreBp >= r.profile.passThresholdBp }]; })) },
  { id: 'parts.aspect-ratio', version: 1, phase: 'assignment', analyze: (c, r) => result('parts.aspect-ratio', c, c.schema.slots.flatMap(slot => { const expected = expectedUnion(slot); const actual = actualUnion(actualsFor(c, slot.slotKey)); if (!expected || !actual) return []; const expectedRatio = expected.width / expected.height; const actualRatio = actual.width / actual.height; const scoreBp = ratioScore(actualRatio, expectedRatio, r.profile.aspectRatioTolerance); return [{ id: slot.slotKey, label: `${slot.label} aspect ratio`, expected: expectedRatio, actual: actualRatio, tolerance: r.profile.aspectRatioTolerance, scoreBp, passed: scoreBp >= r.profile.passThresholdBp }]; })) },
  { id: 'parts.shape', version: 1, phase: 'assignment', analyze: c => result('parts.shape', c, c.schema.slots.flatMap(slot => actualsFor(c, slot.slotKey).map((actual, index) => { const expected = slot.components[index]; const scoreBp = expected ? clampBp(maskSimilarity(actual.shapeMask, expected.shapeMask) * 10000) : 0; return { id: `${slot.slotKey}.${index}`, label: `${slot.label} shape`, expected: expected ? 'reference mask' : 'missing', actual: 'observed mask', scoreBp, passed: scoreBp >= c.schema.matcherProfile.passThresholdBp }; }))) },
  { id: 'relations.size-ratio', version: 1, phase: 'relational', analyze: c => result('relations.size-ratio', c, c.schema.matcherProfile.sizeRatioRules.flatMap(rule => { const left = metric(actualsFor(c, rule.leftSlotKey), rule.metric); const right = metric(actualsFor(c, rule.rightSlotKey), rule.metric); if (!left || !right) return []; const actual = left / right; const expectedLeft = expectedMetric(c.schema.slots.find(slot => slot.slotKey === rule.leftSlotKey), rule.metric); const expectedRight = expectedMetric(c.schema.slots.find(slot => slot.slotKey === rule.rightSlotKey), rule.metric); const scoreBp = ratioScore(actual, rule.expectedRatio, rule.tolerance); return [{ id: rule.ruleId, label: `${rule.leftSlotKey} / ${rule.rightSlotKey}`, expected: { metric: rule.metric, left: expectedLeft, right: expectedRight, ratio: rule.expectedRatio }, actual: { metric: rule.metric, left, right, ratio: actual }, tolerance: rule.tolerance, scoreBp, passed: scoreBp >= c.schema.matcherProfile.passThresholdBp }]; })) },
  { id: 'assignment.coverage', version: 1, phase: 'assignment', analyze: (c: ComparisonContext): AnalyzerResult => { const checks: MetricCheck[] = c.schema.slots.map(slot => { const present = (assignmentFor(c, slot.slotKey)?.componentIds.length ?? 0) > 0; return { id: slot.slotKey, label: `${slot.label} coverage`, expected: slot.required ? 'required' : 'optional', actual: present ? 'assigned' : 'missing', scoreBp: present ? 10000 : slot.required ? 0 : 5000, passed: present || !slot.required }; }); if (c.unmatchedComponentIds.length) checks.push({ id: 'extras', label: 'Extra islands', expected: 0, actual: c.unmatchedComponentIds.length, scoreBp: clampBp(10000 - c.unmatchedComponentIds.length * 1500), passed: false }); return result('assignment.coverage', c, checks); } },
];
